dataset: biasbios
output_dir: outputs/biasbios


erasure_model:
  name: TACO

erasure_model_init_params:
  method_decompose: PCA
  num_components: 100
  n_concepts_to_remove: 1
  epochs: 50
  verbose: true

seed: 123

